apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: ${KUBEVIRT_NAMESPACE}
  annotations:
    argocd.argoproj.io/sync-wave: "2" # Deploy after operator CRDs are available
spec:
  configuration:
    network:
      defaultNetworkInterface: masquerade
  infra:
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
  workloads:
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
