ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4PodCIDRList:
      - ${POD_CIDR}

kubeProxyReplacement: true

# Allow Cilium to run on controlplane nodes
tolerations:
  - operator: Exists
  
securityContext:
  capabilities:
    ciliumAgent:
      - CAP_NET_BIND_SERVICE
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE

cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

k8sServiceHost: "127.0.0.1"
k8sServicePort: 7445

gatewayAPI:
  enabled: true
  enableAlpn: true
  enableAppProtocol: true

encryption:
  enabled: true
  type: wireguard
  nodeEncryption: true
  wireguard:
    persistentKeepalive: 5s


ingressController:
  enabled: true
  default: true
  loadbalancerMode: shared


#Needed or else ArgoCD will show resources as OutOfSync permanently
hubble:
  tls: #https://docs.cilium.io/en/latest/observability/hubble/configuration/tls/
    auto: # https://docs.cilium.io/en/latest/configuration/argocd-issues/#argo-cd-show-resources-permanently-out-of-sync
      enabled: true
      method: certmanager
      certValidityDuration: 60 #Days
      certManagerIssuerRef:
        name: ${TALOS_CLUSTER_NAME}-ca-issuer
        kind: ClusterIssuer