apiVersion: v1
kind: Secret
metadata:
  name: longhorn-backup-default-target-credentials
type: Opaque
stringData:
  CIFS_USERNAME: "${LONGHORN_BACKUP_TARGET_USERNAME}"
  CIFS_PASSWORD: "${LONGHORN_BACKUP_TARGET_PASSWORD}"