
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitea-runner-vol
  namespace: ${GITEA_NAMESPACE}-runners
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: globalenc-1replica-notretained
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitea-runner
  name: gitea-runner
  namespace: ${GITEA_NAMESPACE}-runners
spec:
  replicas: 1
  
  selector:
    matchLabels:
      app: gitea-runner
  strategy:
    type: Recreate
  template:
    
    metadata:
      labels:
        app: gitea-runner
    spec:
      serviceAccountName: gitea-runner-service-account
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
      volumes:
      - name: runner-config
        configMap:
          name: runner-conf
      - name: runner-setup-envs
        configMap:
          name: runner-setup-envs
          defaultMode: 493
      - name: runner-data
        persistentVolumeClaim:
          claimName: gitea-runner-vol
      - name: cluster-ca # Mount cluster CA bundle to trust internal cluster certs like Gitea
        configMap:
          name: cluster-ca-bundle
          items:
            - key: ca.crt
              path: cluster-ca.crt


      initContainers:
        - imagePullPolicy: Always
          name: setup-env-file
          securityContext:
            runAsNonRoot: false
            readOnlyRootFilesystem: false
            privileged: false
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: runner-data
              mountPath: /data
            - name: runner-setup-envs
              mountPath: /setupEnvs
          image: ubuntu:latest
          command: 
            - /setupEnvs/saveEnvs.sh
      containers:
      - name: runner
        image: gitea/act_runner:${GITEA_RUNNERS_IMAGE_TAG}
        imagePullPolicy: Always
        # command: ["sh", "-c", "while ! nc -z localhost 2376 </dev/null; do echo 'waiting for docker daemon...'; sleep 5; done; /sbin/tini -- /opt/act/run.sh"]
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: 250m
            memory: "0.5Gi"
        env:
        - name: CONFIG_FILE
          value: /config/runner-config.yaml
        # - name: DOCKER_HOST
        #   value: tcp://localhost:2376
        #   #value: /data/.docker/run/docker.sock
        # - name: DOCKER_CERT_PATH
        #   value: /certs/client
        # - name: DOCKER_TLS_VERIFY
        #   value: "1"
        # - name: DOCKER_HOST
        #   value: unix:///run/user/1000/docker.sock  # Rootless socket path
        #- name: GITEA_RUNNER_JOB_CONTAINER_NETWORK
        #  value:  #Sets job containers networks name, defaults to bridge
        - name: GITEA_INSTANCE_URL
          value: https://${GITEA_DOMAIN_NAME}
        - name: GITEA_RUNNER_REGISTRATION_TOKEN
          valueFrom:
            secretKeyRef:
              name: runner-registration-token
              key: token
        #- name: GITEA_RUNNER_LABELS
        #  value: ubuntu-latest:docker://ubuntu:latest,ubuntu-bengtan:docker://ubuntu:bengt #NOTE NOTE need to re-register with new token if changed
          #value: ubuntu-latest:docker://catthehacker/ubuntu:runner-22.04,ubuntu-22.04:docker://catthehacker/ubuntu:runner-22.04,ubuntu-20.04:docker://catthehacker/ubuntu:runner-20.04
        
        securityContext:
          privileged: true
        volumeMounts:
        - name: runner-data
          mountPath: /data

        - name: runner-config
          mountPath: /config
        - name: cluster-ca # Mount cluster CA bundle to trust internal cluster certs like Gitea
          mountPath: /etc/ssl/certs/cluster-ca.crt
          subPath: cluster-ca.crt
          readOnly: true
        